// <auto-generated />
using System;
using Garimpei.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Garimpei.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712174042_AddLojaEntity")]
    partial class AddLojaEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Garimpei.Domain.Entities.Busca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Categorias")
                        .HasColumnType("text[]");

                    b.Property<decimal?>("ComissaoMin")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Fontes")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .HasColumnType("text[]");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("Marketplaces")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<long[]>("ShopIds")
                        .HasColumnType("bigint[]");

                    b.Property<string>("ShopNames")
                        .HasColumnType("jsonb");

                    b.Property<string>("SortBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VendasMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.ToTable("Buscas");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.CouponAlertHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("AlertedDiscountValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CouponId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.HasIndex("CouponId", "AlertRuleId", "AlertedAt");

                    b.ToTable("CouponAlertHistories");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.CouponAlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Marketplaces")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MinDiscount")
                        .HasColumnType("double precision");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.ToTable("CouponAlertRules");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Destino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Favorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<double>("Comissao")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Loja")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<string>("ProdutoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.HasIndex("OwnerUid", "ProdutoId")
                        .IsUnique();

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrigemPadrao")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.HasIndex("ShopId", "Marketplace", "OwnerUid")
                        .IsUnique();

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShopName")
                        .HasColumnType("text");

                    b.Property<int>("Sold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.HasIndex("ItemId", "ShopId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Publicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AgendadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<double>("Comissao")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinoId")
                        .HasColumnType("text");

                    b.Property<string>("Detalhe")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnviadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estrategia")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<string>("ProdutoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.HasIndex("Status");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ComFoto")
                        .HasColumnType("boolean");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Garimpei.Domain.Entities.TenantConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AceitouTermosEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AlertaApenasQuedas")
                        .HasColumnType("boolean");

                    b.Property<double>("AlertaThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("AmazonAccessKeyEnc")
                        .HasColumnType("text");

                    b.Property<string>("AmazonPartnerTag")
                        .HasColumnType("text");

                    b.Property<string>("AmazonSecretKeyEnc")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopeeAppId")
                        .HasColumnType("text");

                    b.Property<string>("ShopeeSecretEnc")
                        .HasColumnType("text");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("text");

                    b.Property<string>("TelegramTokenEnc")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsappPhoneNumberId")
                        .HasColumnType("text");

                    b.Property<string>("WhatsappTokenEnc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid")
                        .IsUnique();

                    b.ToTable("TenantConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
